schema_version: 1

context:
  name: batchgeneratorsv2
  version: "0.3.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/batchgeneratorsv2-${{ version }}.tar.gz
  sha256: 54b12eec1ed92f234f0e26c04b79e4f3670abb760c2603b7fc02c62c8e7b6e46

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pytorch >=2.0.0
    - numpy
    - batchgenerators >=0.25

tests:
  - python:
      imports:
        - batchgeneratorsv2
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Batchgenerators but better
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/MIC-DKFZ/batchgeneratorsv2

extra:
  recipe-maintainers:
    - jan-janssen
